<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>72056135-20aa-4394-9487-34e28d72bad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;adplus-dvertising&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c53ebc9-b5a1-436d-8842-65d6c523a981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ad.plus/adplus-advertising.svg</value>
      <webElementGuid>f23f586c-0850-4aed-afc7-c944ce25ff78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>adplus-dvertising</value>
      <webElementGuid>56418890-80f2-47cb-94c0-3bbfae2f9bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ad.Plus Advertising</value>
      <webElementGuid>452d7444-ac86-473f-83b4-d4370b50739b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)/img[1]</value>
      <webElementGuid>6cc0dcc1-f5e4-4f57-8e07-f8b4a36f7004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']/img</value>
      <webElementGuid>9e29ee0b-2b42-42f7-905a-dfe2f01a3703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='adplus-dvertising']</value>
      <webElementGuid>08ebd04e-aeb3-4dda-99be-c76e60c14b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>31016713-d37d-4c34-93bd-ad0a870a2755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ad.plus/adplus-advertising.svg' and @alt = 'adplus-dvertising' and @title = 'Ad.Plus Advertising']</value>
      <webElementGuid>f61b96d5-81d7-41a4-a438-b36c8bf5e6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
