<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Password</name>
   <tag></tag>
   <elementGuidId>faf28dab-fe24-4c58-a021-de69593e1947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d918304-ff8f-4899-9a81-288b68b6c947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b5d15de6-425e-415b-b5a8-c586a8da5e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c11b8563-a5d5-4535-b953-8758aba750a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1a6dc688-6dee-4198-9246-4f841c65741a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dfe37b16-8cf9-4d04-b111-4a386be44217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password&quot;)</value>
      <webElementGuid>770537b2-f057-4d7f-bfff-f074fab56e85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Password']</value>
      <webElementGuid>96acd23c-5409-4053-bf7d-705cc2a74396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>6d7279a1-74ac-4c05-90ec-77d4686ad69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Password' and @name = 'Password' and @type = 'password']</value>
      <webElementGuid>28edc65e-1eea-40b7-93a6-af7cd849348c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
